# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lightrag2',
                'doc_host': 'https://adamaslan.github.io',
                'git_url': 'https://github.com/adamaslan/lightrag2',
                'lib_path': 'lightrag2'},
  'syms': {'lightrag2.core': {'lightrag2.core.foo': ('core.html#foo', 'lightrag2/core.py')}}}
